### PR TITLE
Add Cargo features and code to allow OpenSSL to be used for Crypto

### PR DESCRIPTION
**Pull request by ramaravishankar**
Hi - thanks for sharing this library!

This change is to add support for using OpenSSL for cryptography instead of the MD5 crate - for cases where only a trusted OpenSSL implementation is supported for anything cryptography related. There's no functional change to the output of the library.

I've added this as a cargo feature so that the MD5 crate is still used by default so as not to impact existing users who don't want the OpenSSL dependency. Using one feature doesn't compile in the dependencies of the other.

I've also added extra workflow steps to test the two feature options explicitly and confirmed these pass.

Let me know if you have any comments.

If you do accept, would you be able to tag a new release as well please?

Thanks again!

### CODE REVIEW

**Comment by ramaravishankar** [comment]
@moznion can I please get a feedback on this?

**Comment by ramaravishankar** [comment]
@moznion  can I please get feedback on this?

**Comment by moznion** [comment]
@ramaravishankar Thank you for your contribution. Please give me a time to take a look at this.

**Comment by ramaravishankar** [comment]
@moznion sorry for bugging again, we have a dependency on this change, would it be possible for you to review this week?

**Review by moznion — APPROVED** [review]

**Comment by moznion** [comment]
@ramaravishankar I really appreciate your contribution! It seems some of Windows tests failed but the core of the change seems good. I'll merge this pull request and publish the new version which includes this change. Once it has been finished, I'll let you know that.

**Comment by moznion** [comment]
@ramaravishankar I published [v0.4.0](https://github.com/moznion/radius-rs/releases/tag/v0.4.0) which includes this change. Thank you for your contribution!

**Comment by ramaravishankar** [comment]
Thanks @moznion, cheers 🎉

**Pull request merged**
